:PROPERTIES:
:ID:       6780ad00-ecff-4bd7-8633-24957bf2bbfa
:END:
#+title: Org learn
#+setupfile: setup.org
#+date: [2024-11-19 Tue 18:28]
#+excerpt: 
#+filetags:

Здесь я буду записывать фичи org-mode.

* Вставка
~C-c .~ -- Вставка даты (Узнать, можно ли поменять формат даты)

~C-c C-l~ -- Вставка ссылки

* Сохранение
~C-x C-w~ -- Сохранить под новым именем

~C-x s~ -- Сохранить все буфферы


* Окна и буфферы
Тут могу быть неточен в том, где буффер, а где окно.

~C-w j~ -- На окно снизу

~C-w k~ -- На окно сверху

~C-w w~ -- Следующее окно

**~C-M-j~ -- Switch buffer**

~C-x 1~ -- Окно на весь экран

~C-x 2~ -- Разделить окно на два


* Шорткаты org
~S-Tab~ -- Сворачивать-разворачивать заголовки

~C-Enter~ -- Ещё один такой же заголовок

~M-стрелка влево-вправо~ -- Изменить уровень заголовка

**~M-стрелка вверх-вниз~ -- Двигать строчку**


* Ссылки
**~C-c C-o~ -- Открыть ссылку**

* Списки
1. Нумерованные -- просто ставишь ~1.~
2. Пишешь текст
3. И нажимаешь ~M-Enter~

~M-S-Enter~ -- Создаёт чекбокс

* Тудушки
~C-c C-t~ -- Done (Или S-стрелочка)

* Agenda
~C-c C-s~ S-стрелочки -- Выбрать дату

~C-c C-d~ -- Дедлайн

* auto-complete
~M+/~ -- Листать варианты 

* Bookmark
~C-x r m~ -- Создать закладку

~C-x r b~ -- Открыть закладку

* Слишком длинная строка
~visual-line-mode~ -- В этом режиме длинные строки будут отображаться с переносом на экране, но физически останутся одной строкой в файле. Иногда этот режим ломается и требуется включить вручную.
