:PROPERTIES:
:ID:       9f95698c-6710-4725-97a3-98f9ec2d4e7c
:END:
#+title: Теорема Бэра о категориях
#+setupfile: setup.org
#+date: [2025-10-16 Thu 04:04]
#+excerpt: 
#+filetags:

Если $(X, \rho)$ - метрическое пространство и $X = \bigcup_{n=1}^{\infty}$ такие, что $\forall n X_n$ \--- $X_n$ нигде не плотно $\Rightarrow$ *$X$ не может быть полным*.

Внимание: $X = \bigcup_{n=1}^{\infty}$ \--- Счётное объединение нигде не плотных множеств.

* Другими словами
#+BEGIN_QUOTE
Полное метрическое пространство нельзя представить в виде счётного объединения нигде не плотных множеств.
#+END_QUOTE

* Почему "Категории"?
Потому что Бэр вводил категории множеств:
- 1-я категория \--- множества, которые можно представить в виде счётного объединения не плотных множеств
- 2-я категория \--- всё остальное (Например полные метрические пространства)

* Nota bene
Теорема Бэра о категориях говорит только о том, что *полное метрическое пространство точно нельзя представить как $\bigcup_{n=1}^{\infty}$*. А про неполное м.п. теорема не говорит ничего.

** Примеры
- $\mathbb{Q}$ \--- неполное. Но его можно представить счётным объединением рациональных точек
- $\mathbb{R} \textbackslash \{0\}$ \--- неполное. И его нельзя представить счётным объединением нигде не плотных множеств. Потому что если бы представили, то $\mathbb{R} \textbackslash \{0\} = \bigcup_{n=1}^{\infty}$. Тогда $\{0\}$ можно было бы перенести вправо, а это значило бы, что мы $\mathbb{R}$ представили бы как $\bigcup_{n=1}^{\infty}$, что противоречит теореме.
