:PROPERTIES:
:ID:       cc85b4a6-fd7e-432d-9537-e2a59c7bf1c3
:END:
#+title: Отображение метрических пространств
#+setupfile: setup.org
#+date: [2025-10-13 Mon 05:03]
#+excerpt: 
#+filetags:

$$(X, \rho) \overset{f}{\rightarrow} (Y, d)$$

:NOTE: Что $f$ делает с метриками?

:NOTE: Возможно, следующие определения следует вывести в отдельную заметку, а здесь оставить ссылки

* Непрерывность
$$
\text{Отображение } f \text{ непрерывно, если } \forall \varepsilon > 0\ \exists \delta = \delta(x_{0}, \varepsilon): 
\forall x_1, x_2: \rho(x_1, x_2) < \delta \implies d(f(x_1), f(x_2)) < \varepsilon.
$$

* Равномерная непрерывность
$$
\text{Отображение } f \text{ равномерно непрерывно, если } \forall \varepsilon > 0\ \exists \delta = \delta(\varepsilon): 
\forall x_1, x_2: \rho(x_1, x_2) < \delta \implies d(f(x_1), f(x_2)) < \varepsilon.
$$

* Липшицево отображение
$$
\text{Отображение } f \text{ - липшицево } (f \in \text{Lip}(X, Y)), \text{ если } \exists r \geq 0: \forall x_1, x_2 \in X: 
d(f(x_1), f(x_2)) \leq r \cdot \rho(x_1, x_2).
$$

Очевидно, что липшицево отображение /равномерно непрерывно/.

** Константа Липшица
$$
\text{Lip}(f) = \sup_{x_1 \neq x_2} \dfrac{d(f(x_1), f(x_2))}{\rho(x_1, x_2)}
$$

*** Сжимающее отображение
Отображение f называется *сжимающим*, если:
1. $f$ - липшицево
2. $r \in [0, 1)$

То есть если существует $r$ *уменьшающий* $\rho$, что всё равно неравенство $d(f(x_1), f(x_2)) \leq r \cdot \rho(x_1, x_2)$ выполняется для любых $x_1, x_2$, то мы называем отображение сжимающим. *Это правильное понимание?*

Может быть другой случай, когда неравенство выполняется только если $r$ играет роль увеличивающего коэффициента.

А может быть случай, когда, какой бы мы $r$ ни взяли, для каких-то $x_1, x_2$ у нас неравенство не выполнится и это значит, что отображение не липшицево. Я так всё это понял.

* Изометрический изоморфизм
Метрические пространства $(X, \rho) и $(Y, d)$ *изометрически изоморфны*, если $\exists f: X \implies Y$ такое, что:
1. $f$ - биекция
2. $\forall x_1, x_2 \in X: \rho(x_1, x_2) = d(f(x_1), f(x_2))$

Такие пространства можно считать *неразличимыми*.

Понятно о чём речь, стоит добавить примеры, когда пространства записываются по-разному -- формально разные, но при этом изометрически изоморфны. Потому что если пространства записываются одинаково, то нет сомнений, что они неразличимы)

* Свойства полных метрических пространств
** Теорема о неподвижной точке
Пусть $(X, \rho)$ -- полное метрическое пространство и $f\colon X \rightarrow X$ -- сжимающее отображение $\implies \exists!x\colon f(x) = x$.

То есть, при действии отображения, эта точка никуда не сдвинулась. Не очевидно почему она единственная.

#+BEGIN_QUOTE
Это очень мощный инструмент в доказательстве теорем о существовании.
#+END_QUOTE
*** Идея доказательства
Берём любую $x_0$, далее определяем $x_{1}= f(x_{0})\dots x_{n+1}=f(x_{n})$.

Это называется *орбитой точки* $x_{0}$: $\text{orb}x_0 = \{x_k\}_{k=0}^{\infty}$. Основная идея в том, что орбита фундаментальна, фундаментальность показывается с помощью сжимаемости, далее пользуемся фактом полноты и показываем, что существует предел $\exists \lim x_{k}=x$. На основе сжимаемости отображения надо будет доказать, что если бы мы выбрали другую начальную точку $x_0$, то предел всё равно был бы тот же.
:NOTE: Пока не очень понятно, но я не пробовал доказать
