:PROPERTIES:
:ID:       2bf90222-6a39-4930-8c05-ea84d6494c14
:END:
#+title: Предельные точки множеств
#+setupfile: setup.org
#+date: [2025-10-10 Fri 04:09]
#+excerpt: 
#+filetags:

* Предельная точка
Точка \( x_0 \) -- предельная точка множества \( M \subset (X, \rho) \), если 
\[ \forall \varepsilon > 0 \;\; B(x_0, \varepsilon) \cap M \] 
содержит бесконечно много точек.

См. [[id:6b9feaef-9718-424f-a229-0372537fcf2e][Предельная точка]].

* Следствие
Если \( x_0 \) -- предельная точка, то 
\[ \exists \{x_n\}_{n=1}^{\infty}, \quad x_n \in M \;\; \text{и} \quad x_n \xrightarrow{\rho} x_0. \]

* Точка прикосновения
Точка \( x_0 \) является точкой прикосновения множества \( M \), если 
\[ \forall \varepsilon > 0 \;\; B(x_0, \varepsilon) \cap M \neq \emptyset. \]

Чем отличаются точки прикосновения от предельных точек? Для точек прикосновения пересечение (из определения) может содержать либо конечное ненулевое число точек, либо бесконечное. Следовательно любая предельная точка является точкой прикосновения, но обратное неверно.

* Изолированная точка
Точка \( x_0 \) называется изолированной для множества \( M \), если 
\[ \exists \varepsilon > 0 \;\; B(x_0, \varepsilon) \cap M = \{x_0\}. \]

:NOTE: Мне показался тонким момент отличия точки прикосновения от изолированной точки. Возможно станет понятнее на специально подобранных множествах.

* Замыкание
Пусть \( M \subset (X, \rho) \), тогда его замыкание 
\[ \overline{M} = M \cup \{\text{все предельные точки}\} = \{\text{все точки прикосновения}\}. \]

* Пример
:NOTE: Это пример из лекции и я его не понял. Может быть 3 это точка прикосновения потому что в её окрестности всегда есть она сама как часть множества... Но если мы принимаем это суждение, то у нас ломается понятие изолированной точки, потому что в любой её окрестности тоже всегда есть она сама. Это даже одна и та же точка в примере. Может быть изолированная точка это просто точка прикосновения, но особого типа -- скорее всего так и есть.

Я так понял, что /все точки прикосновения $=$ предельные точки $\cup$ изолированные точки/.

Пусть \( X = \mathbb{R}, \;\; \rho(x, y) = |x - y|, \quad M = [1;2) \cup \{3\} \).

- Предельные точки: все точки отрезка \( [1;2] \)
- Точки прикосновения: \( [1;2] \cup \{3\} \)
- Изолированная точка: \( \{3\} \)
  
* Свойства замыкания
1. \( \overline{M} \) - замкнутое множество
2. \( \overline{\overline{M}} = M \)
