:PROPERTIES:
:ID:       0284c782-b8a9-4552-aecd-27c660e45f21
:END:
#+title: Кофе
#+setupfile: setup.org
#+date: [2025-03-02 Sun 19:37]
#+excerpt: 
#+filetags:

Как-то давно думал зашарить за кофе, объясняя это желание тем, что не зря же в этом деле столько знатоков. На протяжении недель несколько раз ходил в кофейню к одному и тому же бариста. И в последний раз случайно назвал кофе средним родом и после этого в украинской кофейне начался сущий кошмар: бариста начал изливаться гневом, что "кофе  — ОН МОЙ" и рассказывать как он страдает, когда слышит, что кофе это "оно".

И всё это при том, что двумя предложениями ранее я согласовал род корректно, как и во все дни, за которые он меня запомнил.

В этой теме подозрительно много слов, которые, как будто, байтят на ошибку: кофе, не склоняющееся "бариста", "двойное экспрессо". Думаете это случайно? Тема кофе идеально подходит для того, чтобы ощутить свою экспертность, не обладая, при этом, содержательными знаниями. Заказывая кофе на одних и тех же зёрнах, всегда получался разный вкус — о какой науке может идти речь? Но зато как заносчиво можно разглагольствовать!

И как можно оправдать стоимость 200-300 рублей за стаканчик капуча? Откуда столь высокая прибавочная стоимость? Можно объяснить это арендой места за стоимость соевого латте, чтобы поворкать в маке или + к деловитости от стаканчика гарден (тюменские поймут, петербуржцы — сорри, сидите в вольчеках), с которым некоторые ходят по полдня.

Всё дело в веществе, о котором все знают, но не говорят. Именно он формирует столь высокую прибавочную стоимость и именно из-за овердоза им на меня сорвался бариста. Представьте себе кайф от самого крутого оргазма в своей жизни, умножьте в тысячу раз и всё равно попадёте пальцем в небо. Когда ты на кофе, у тебя только одна забота — вмазаться и то самое вещество, с которого так трудно соскочить — пероральный снобизм.
