:PROPERTIES:
:ID:       07efdef6-e870-4b0e-8187-9601d951f3f1
:END:
#+title: analysis_1_lecture_4
#+setupfile: setup.org
#+date: [2024-12-27 Fri 00:30]
#+excerpt: 
#+filetags: :analysis:

* Лемма о зажатом пределе
Это теорема о двух миллиционерах, ничего сложного.

* Бесконечно малая последовательность
Бесконечно малая последовательность -- если её предел равен нулю.

Произведение бесконечно малой последовательности на ограниченную даёт бесконечно малую последовательность.

* Точные верхние и нижние грани
$b$ -- верхняя грань множества, если $\forall a \in A \;\; a \leqslant b$

Если множество имеет верхнюю/нижнюю грань, то оно называется ограниченным сверху/снизу.

Наименьшая из верхних граней множества $A$, называется точной верхней гранью и обозначается $\sup A$

Аналогично, наибольшая из нижних граней называется точной нижней гранью и обозначается $\inf A$.

* О существовании точной верхней грани :theorem:
:PROPERTIES:
:ID:       bfb932eb-f26b-4e37-9cad-c816cdadf24e
:END:
Пусть $A$ -- непустое ограниченное сверху множество, тогда существует $\sup A$.

Доказательство: Рассмотреть множество верхних граней $B$, заметить, что оно лежит левее $A$ и по принципу полноты $A \text{и} B$ разделяет точная верхняя грань $c = \sup A$.

* Невозрастающая последовательность
Если $\forall n \in \mathbb{N} \;\; a_{n+1} \leqslant a_{n}$, то такая последовательность называется *невозрастающей*.

Если $\forall n \in \mathbb{N} \;\; a_{n+1} \geqslant a_{n}$ -- *неубывающая*.

Невозрастающие и неубывающие последовательности называются *монотонными*

* Теорема Вейерштрасса :theorem:
Пусть последовательность $\{a_{n}\}$ -- монотонна и ограничена, тогда она имеет предел.

Доказательство: по [[id:bfb932eb-f26b-4e37-9cad-c816cdadf24e][теореме о существовании точной верхней грани]], у множества элементов последовательности есть $\sup$.

* Последовательность $a_{n} = (1 + \dfrac{1}{n})^{n}$ имеет предел  :theorem:
Доказал Бернулли. Банковская задача.

* Число e                                                        :definition:
Число $e$ -- это предел последовательности $(1 + \dfrac{1}{n})^{n}$
