:PROPERTIES:
:ID:       6f8236e0-04fc-4e8c-a7a8-aef3d2e415db
:END:
#+title: analysis_1_seminar_1
#+setupfile: setup.org
#+date: [2024-11-20 Wed 00:27]
#+excerpt: 
#+filetags: :analysis:

* Найти обыкновенную дробь из периодической
- $2.13(9714)$

* Найти сумму всех правильных положительных десятичных дробей с периодом, состоящим из цифр 2, 3, 4, 5, 6
Например, такие дроби: $0.(23456)$, $0.(34256)$ и т.п.

Пар $5! = 120$ Числу $0.(23456)$ соответствует число $0.(65432)$, их сумма равна $0.(8)$. Любому числу из этих 120 найдётся пара. Всего пар 60, значит сумма равна $0.(8) \cdot 60$. $0.(8) = \dfrac{8}{9}$, значит искомая сумма равна $\dfrac{160}{3}$

* Доказать иррациональность $\sqrt{3}$
Предположить обратное. Доказать, что числитель делится на 3 и знаменатель делится на 3, а значит дробь сократима, а значит противоречие.

* Доказать иррациональность $\sqrt{2} + \sqrt{3}$
Указание: Сначала возвести обе части в квадрат: $\sqrt{2} + \sqrt{3} = \dfrac{p}{q}$. Сумма рациональных чисел -- рациональное число.

* Доказать иррациональность $\sin\dfrac{\pi}{9}$
$\sin\dfrac{\pi}{3} = \sin(3\cdot\dfrac{\pi}{9})$. Раскрыть по синусу тройного угла (Синус тройного угла можно вывести из формулы синуса суммы).

* Вывод формулы геометрической прогрессии
$$
S = 1 + q + q^2 + \dots + q^n
$$

$$
S = q + q^2 + \dots + q^{n+1}
$$

Вычтем из второго первое:

$$
S(q - 1) = q^{n+1} - 1
$$

Искомая формула:

$$
S = \dfrac{q^{n+1} - 1}{q - 1}
$$

* Найти сумму

$S = \Sigma\dfrac{1}{n(n+1)}$

Указание: заметить, что $\dfrac{(n + 1) - n}{n(n+1)}$

* Найти сумму 1 + 11 + 111 + 1111...

$1 + 11 + 111 \dots = S$

$9 + 99 + 999 \dots = 9S$

$10 + 10^2 + 10^3 \dots + 10^n - n = 9S$

А это уже геометрическая прогрессия.

* Доказать формулу суммы арифметической прогрессии по индукции
