:PROPERTIES:
:ID:       35540f17-78a1-4d7a-a012-b47bd72d6383
:END:
#+title: numbers
#+setupfile: ./setup.org
#+date: [2024-11-09 Sat 20:06]
#+excerpt:
#+filetags: :private:

* Рациональные числа
#+BEGIN_LaTeX
$$
\mathbb{Q} = \left\{ \frac{a}{b} \mid a \in \mathbb{Z}, b \in \mathbb{N}, (a, b) = 1 \right\}
$$

$(a, b) = 1$ Значит, что $НОД = 1$. То есть дробь несократима.
#+END_LaTeX

* Иррациональность $\sqrt{2}$
\begin{gather*}
x^2 = 2 \\
x = \dfrac{a}{b} \iff 2 = \dfrac{a^2}{b^2} \iff 2b^2 = a^2 \iff \\
\iff a \text{ делится на } 4 \iff a^2 = 4k, k \in \mathbb{N} \iff b^2 = 2k \iff \\ 
\iff a \text{ и } b - \text{чётные, а значит сократимые}
\end{gather*}

* $A$ лежит левее $B$
:PROPERTIES:
:ID:       bd54e8a9-ee81-4864-b517-db149c650aac
:END:

Числовое множество $A$ лежит левее числового множества $B$ $\iff$ $\forall a \in A \text{ и } \forall b \in B \colon a \leqslant b$

* Разделяющий элемент
Число $c$ называется разделяющим элементом для множеств $A$ и $B$ из [[id:bd54e8a9-ee81-4864-b517-db149c650aac][Предыдущего определения]], если $\forall a \in A\;\; c \geqslant a \text{ и } \forall b \in B\;\; c \leqslant b$.

** Пример
Рассмотреть 2 множества: одно состоит из рациональных чисел, меньших $\sqrt{2}$, а другое из рациональных чисел, больших $\sqrt{2}$. Попробовать найти рациональное число, разделяющее эти 2 множества. Подсказка: рассмотреть число, чуть-чуть меньшее, чем $\sqrt{2}$, понять, что нужное нам число не может быть меньше $\sqrt{2}$. Затем рассмотреть число, большее чем $\sqrt{2}$ и тоже понять, что оно не может быть больше, чем $\sqrt{2}$.

* Свойство полноты
Числовое множество $M$ обладает свойством полноты, если для любых его непустых подмножеств $A$ и $B$, таких, что $A \leqslant B\;\;\exists c \in M$, которое разделяет $A$ и $B$.

$\mathbb{Q}$ не обладает свойством полноты.

$\mathbb{N}$ обладает свойством полноты.

Рациональные числа могут быть записаны в виде периодических десятичных дробей. Просто потому что когда мы будем числитель делить в столбик на знаменатель, у нас будет конечное число остатков. Всегда появится цикл. См. теорему о периодичности десятичных дробей для рациональных чисел.

* Иррациональные числа
**Иррациональные числа** -- числа которые представляются в виде бесконечных непериодических десятичных дробей.

* Вещественные числа
Множество всех периодических и непериодических десятичных дробей называется множеством **вещественных чисел**.

* Важный момент
У тех дробей, у которых возможен период из $(9)$, всегда возможен период из $(0)

$$4,(9) = 5,(0)$$

Запретим периоды из девяток, чтобы была однозначность.

* Принцип полноты для $\mathbb{R}$
:PROPERTIES:
:ID:       6bb02af9-7601-4953-a124-ec24c47d567f
:END:
Для вещественных чисел выполнен принцип полноты.

Это сложная формула:

$$
\mathbf{A} = \begin{matrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{matrix}, \\
\mathbf{B} = \begin{matrix}
b_{11} & b_{12} & \cdots & b_{1p} \\
b_{21} & b_{22} & \cdots & b_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \cdots & b_{np}
\end{matrix}, \\
\mathbf{C} = \mathbf{A} \cdot \mathbf{B} = \begin{matrix}
\sum_{k=1}^n a_{1k}b_{k1} & \sum_{k=1}^n a_{1k}b_{k2} & \cdots & \sum_{k=1}^n a_{1k}b_{kp} \\
\sum_{k=1}^n a_{2k}b_{k1} & \sum_{k=1}^n a_{2k}b_{k2} & \cdots & \sum_{k=1}^n a_{2k}b_{kp} \\
\vdots & \vdots & \ddots & \vdots \\
\sum_{k=1}^n a_{mk}b_{k1} & \sum_{k=1}^n a_{mk}b_{k2} & \cdots & \sum_{k=1}^n a_{mk}b_{kp}
\end{matrix},
\text{где } \mathbf{C}_{ij} = \sum_{k=1}^n a_{ik}b_{kj} \quad \text{для } i = 1, 2, \ldots, m \text{ и } j = 1, 2, \ldots, p.
$$
